[package]
name = "cloud-storage-bridge"
version = "0.1.0"
description = "Upload folder media content to a Cloudflare R2 bucket"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "cloud_storage_bridge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
mime_guess = "2"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
aws-smithy-runtime-api = "1"
aws-smithy-types = "1"
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs", "std", "tls12", "logging"] }
rustls-native-certs = "0.8"
hyper-rustls = { version = "0.27", default-features = false, features = ["http1", "native-tokio", "tls12", "logging"] }
hyper-util = { version = "0.1", default-features = false, features = ["client", "client-legacy", "http1", "tokio"] }
aws-sdk-s3 = "1"
tokio = { version = "1", features = ["full"] }
notify = "7"
